default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :development, :DB_USERNAME) %>
  password: <%= Rails.application.credentials.dig(:database, :development, :DB_PASSWORD) %>
  host: <%= Rails.application.credentials.dig(:database, :development, :DB_HOST) %>
  database: <%= Rails.application.credentials.dig(:database, :development, :DB_NAME) %>
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  username: <%= Rails.application.credentials.dig(:database, :production, :DB_USERNAME) %>
  password: <%= Rails.application.credentials.dig(:database, :production, :DB_PASSWORD) %>
  host: <%= Rails.application.credentials.dig(:database, :production, :DB_HOST) %>
  database: <%= Rails.application.credentials.dig(:database, :production, :DB_NAME) %>
