development:
  secret_key_base: <%= Rails.application.credentials.dig(:development, :SECRET_KEY_BASE) %>

production:
  secret_key_base: <%= Rails.application.credentials.dig(:production, :SECRET_KEY_BASE) %>
